<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<IsTestProject>false</IsTestProject>
		<AssemblyName>TestFramework.Container.Web.SampleApi</AssemblyName>
		<RootNamespace>TestFramework.Container.Web.SampleApi</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
	</ItemGroup>

</Project>
